a= int(input ("чиcлo 1 в модуле: "))
b= int (input ("чиcлo 2 в модуле: "))
Add=abs(a+b)
R=abs(a-b)
D=abs(a*b)
Y=abs(a/b)
print("Сумма: ", Add)
print("Разность: ", R)
print("произведение: ", D)
print("Частное: ", Y)